services:
 myapp:
  platform: linux/${GUEST_ARCH:-386}
  privileged: true
  devices:
    - "/dev/fuse:/dev/fuse"
  build:
    context: script
    dockerfile: Dockerfile
  volumes:
    - .:/app:Z   # bind current directory to /app in container
  working_dir: /app
  tty: true    # optional, keeps container running for interactive shell
