#!/bin/bash
shopt -s extglob
shopt -s globstar

curl -u "${OBS_USER}:${OBS_PASSWORD}"   -X POST   "https://api.opensuse.org/source/home:qr243vbi/nekobox?cmd=runservice"
curl -u "${OBS_USER}:${OBS_PASSWORD}" \
  "https://api.opensuse.org/source/network:vpn/nekobox/nekobox.changes" \
  -o nekobox.changes

export pkgver="$INPUT_VERSION"
export source_0="https://github.com/qr243vbi/nekobox/releases/download/$pkgver/nekobox-unified-source-$pkgver.tar.xz"

curl -L https://gitea.com/qr243vbi/nekobox/raw/branch/main/nekobox.spec -o nekobox.spec
curl -L https://gitea.com/qr243vbi/nekobox/raw/branch/main/nekobox-core.spec.in -o nekobox-core.spec.in
curl -L https://gitea.com/qr243vbi/nekobox/raw/branch/main/nekobox-qt.spec.in -o nekobox-qt.spec.in

sed -i "s@Version:.*@Version:        $pkgver@g;" nekobox.spec

file_0="$(basename "${source_0}")"

curl -L "${source_0}" -o "${file_0}"

python -c "
import os
text = ''
if os.path.exists('nekobox.changes'):
 f=open('nekobox.changes', 'r')
 text=f.read()
 f.close()
msg='''${MESSAGE}'''
import textwrap
def wrap_preserve_newlines(text, width):
 return '\n'.join([textwrap.fill(line, width) if line.strip() else '' for line in text.splitlines()])
if len(msg) > 0 and 'Update to ${pkgver}' not in text:
 msg = wrap_preserve_newlines(msg, 65)
 if msg[-1] != '\n':
  msg = msg + '\n'
 k='-------------------------------------------------------------------'
 k+='\n$(date) - ${USER} <${EMAIL}>\n\n'
 k+='Update to ${pkgver}\n' + msg + '\n'
 text=k+text
 f=open('nekobox.changes', 'w')
 f.write(text)
 f.close()
print(text)
"

curl -s -u "${OBS_USER}:${OBS_PASSWORD}"   "https://api.opensuse.org/source/network:vpn/nekobox" | grep -oP '<entry[^>]*\sname="\K[^"]+' | while IFS= read -r name
do
curl -u "${OBS_USER}:${OBS_PASSWORD}" -X DELETE "https://api.opensuse.org/source/network:vpn/nekobox/${name}"
done

for i in nekobox.changes nekobox.spec nekobox-core.spec.in nekobox-qt.spec.in "${file_0}"
do
curl -u "${OBS_USER}:${OBS_PASSWORD}" \
  -X PUT \
  -H "Content-Type: text/plain" \
  --data-binary @${i} \
  "https://api.opensuse.org/source/network:vpn/nekobox/${i}"
done

if [[ "$SUBMIT_FACTORY" == 'true' ]]
then
newline="$(echo -e '\n ')"
curl -u "${OBS_USER}:${OBS_PASSWORD}"   -X POST   -H "Content-Type: application/xml"   -d '
<request>
  <action type="submit">
    <source project="network:vpn" package="nekobox"/>
    <target project="openSUSE:Factory" package="nekobox"/>
  </action>
  <description>'"Update to $pkgver. ${newline}${MESSAGE}${newline}${newline} Generated by Github Actions."'</description>
</request>'   'https://api.opensuse.org/request?cmd=create'
fi

