# The URL the site will be built for
base_url = "https://qr243vbi.github.io/nekobox"
title = "NekoBox"
description = "NekoBox"

build_search_index = true
default_language = "en"
generate_feeds = true
generate_sitemap = true

[markdown]
bottom_footnotes = true

[extra]
logo_text = "NekoBox"
logo_image_path = "images/NekoBox.png"
default_thumbnail = "images/NekoBox.png"
default_colorset = "dark"
gtag = ""
sidebar_expand_depth = 1
disable_root_sidebar_hide = false

nav = [
    { name = "Documents", url = "/introduction", type = "url", icon = "bi bi-book" },
    { name = "GitHub", url = "https://github.com/qr243vbi/NekoBox", type = "url", icon = "bi bi-github" },
]
highlighting = true
