name: NyameBox build matrix
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag and version"
        required: true
      publish:
        description: "Publish Release"
        type: boolean
        default: true
        required: true
      text:
        description: "Release Description"
        required: false
      source_only:
        description: "Skip building binaries, distribute only unified source"
        type: boolean
        default: false
        required: false
      binary_only:
        description: "Skip building sources, distribute only binary package"
        type: boolean
        default: false
        required: false
      skip_updater:
        description: "Ship binaries without updater"
        type: boolean
        required: false
        default: false
      build_windows_x64:
        description: "Build windows x64 binaries"
        type: boolean
        default: true
        required: false
      build_windows_arm64:
        description: "Build windows ARM64 binaries"
        type: boolean
        default: true
        required: false
      build_windows_x86:
        description: "Build windows x86 binaries"
        type: boolean
        default: true
        required: false
      build_ubuntu:
        description: "Build linux x64 binaries"
        type: boolean
        default: true
        required: false
      build_ubuntu_arm:
        description: "Build linux ARM64 binaries"
        type: boolean
        default: true
        required: false
      build_ubuntu_32:
        description: "Build linux x86 binaries"
        type: boolean
        default: true
        required: false
      build_ubuntu_arm_32:
        description: "Build linux ARM binaries"
        type: boolean
        default: true
        required: false
      publish_chocolatey:
        description: "Publish chocolatey packages"
        type: boolean
        default: true
        required: false
      publish_winget:
        description: "Publish WinGet manifest"
        type: boolean
        default: true
        required: false
      publish_suse:
        description: "Publish to openSUSE Factory"
        type: boolean
        default: true
        required: false
      publish_copr:
        description: "Publish to COPR"
        type: boolean
        default: true
        required: false
      publish_obs:
        description: "Publish to OBS"
        type: boolean
        default: true
        required: false
      publish_aur:
        description: "Publish to AUR"
        type: boolean
        default: true
        required: false
jobs:
  build-go:
    permissions:
      contents: write
      actions: read
    env:
      INPUT_VERSION: ${{ github.event.inputs.tag }}
    strategy:
  #    max-parallel: 1
      matrix:
        include:
          - cross_os: public
            cross_arch: public
            go_version: "1.25.9"
          - cross_os: linux
            cross_arch: amd64
            allow: ${{ github.event.inputs.build_ubuntu }}
            go_version: "1.25.9"
          - cross_os: linux
            cross_arch: arm64
            allow: ${{ github.event.inputs.build_ubuntu_arm }}
            go_version: "1.25.9"
          - cross_os: linux
            cross_arch: 386
            allow: ${{ github.event.inputs.build_ubuntu_32 }}
            go_version: "1.25.9"
          - cross_os: linux
            cross_arch: arm
            allow: ${{ github.event.inputs.build_ubuntu_arm_32 }}
            go_version: "1.25.9"
          - cross_os: windows
            cross_arch: amd64
            allow: ${{ github.event.inputs.build_windows_x64 }}
            go_version: "1.25.9"
          - cross_os: windows
            cross_arch: arm64
            allow: ${{ github.event.inputs.build_windows_arm64 }}
            go_version: "1.25.9"
          - cross_os: windows
            cross_arch: 386
            allow: ${{ github.event.inputs.build_windows_x86 }}
            go_version: "1.25.9"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checking out sources
        if: matrix.cross_os == 'public' || ( github.event.inputs.source_only  != 'true' && matrix.allow == 'true' )
        uses: actions/checkout@main
        with:
          ref: 'main'
          submodules: 'true'
      - name: Cache Common Download
        id: cache-common
        if: matrix.cross_os != 'public' && ( github.event.inputs.source_only  != 'true' && matrix.allow == 'true' )
        uses: actions/cache@main
        with:
          path: ./deployment
          key: CommonCache-${{ matrix.cross_os }}-${{ matrix.cross_arch }}-${{ hashFiles('script/build_go.sh', 'core/*') }}-${{ matrix.go_version }}
      - name: Install Golang
        if: ( matrix.cross_os == 'public' || ( github.event.inputs.source_only  != 'true' && matrix.allow == 'true' ) ) && steps.cache-common.outputs.cache-hit != 'true'
        uses: actions/setup-go@main
        with:            
          go-version: ${{ matrix.go_version }}
          cache-dependency-path: |
            core/server/go.sum
      - name: Linux - Install apt dependencies
        if: matrix.cross_os == 'public' || ( github.event.inputs.source_only  != 'true' && matrix.allow == 'true' )
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: thrift-compiler
          version: 1.0
      - name: Build golang parts
        if: steps.cache-common.outputs.cache-hit != 'true' && matrix.cross_os != 'public' && ( github.event.inputs.source_only  != 'true' && matrix.allow == 'true' )
        shell: bash
        run: |
          if [[ ${{ github.event.inputs.skip_updater }} == 'true' ]]; then
            export SKIP_UPDATER=ON
          else
            export SKIP_UPDATER=OFF
          fi
          GO_MOD_TIDY=ON GOOS=${{ matrix.cross_os }} GOARCH=${{ matrix.cross_arch }} ./script/build_go.sh
      - name: Build vendor
        if: matrix.cross_os == 'public'
        shell: bash
        run: |
          env INPUT_VERSION=${{ github.event.inputs.tag }} bash -x ./script/deploy_vendor.sh
      - name: Publish sources
        if: matrix.cross_os == 'public' && github.event.inputs.publish == 'true' && github.event.inputs.binary_only == 'false'
        env:
          INPUT_VERSION: ${{ github.event.inputs.tag }}
          MESSAGE: ${{ github.event.inputs.text }}
          GH_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        run: |
          export MESSAGE="$(echo -e "${MESSAGE}")"
          if ! gh release view "${INPUT_VERSION}" >/dev/null 2>&1
          then
            gh release create "${INPUT_VERSION}" --title "${INPUT_VERSION}" --notes "${MESSAGE}"
          fi
          gh release upload "${INPUT_VERSION}" deployment/* --clobber
      - name: Tar files
        if: matrix.cross_os == 'public' || ( github.event.inputs.source_only  != 'true' && matrix.allow == 'true' )
        run: tar czvf artifacts.tgz ./deployment
      - name: Uploading Artifact
        if: matrix.cross_os == 'public' || ( github.event.inputs.source_only  != 'true' && matrix.allow == 'true' )
        uses: actions/upload-artifact@main
        with:
          name: nekobox-${{ github.sha }}-Common-${{ matrix.cross_os }}-${{ matrix.cross_arch }}
          path: artifacts.tgz
  upload_aur:
    name: Upload to Open Build Service and Aur
    permissions:
      contents: read
    needs:
      - build-go
    runs-on: ubuntu-latest
    if: github.event.inputs.publish == 'true' && github.event.inputs.binary_only == 'false'
    steps:
      - name: Checking out sources
        uses: actions/checkout@main
        with:
          ref: 'main'
          submodules: 'true'

      - name: Create requirements.txt, add ssh key
        shell: bash
        env:
          AUR_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        run: |
          echo copr > requirements.txt
    #      git config --global user.email "${{ secrets.EMAIL }}"
    #      git config --global user.name "${{ github.actor }}"
    #      mkdir -p ~/.ssh
    #      touch ~/.ssh/config           ||:
    #      touch ~/.ssh/known_hosts      ||:
    #      echo "Host aur aur.archlinux.org"     >> ~/.ssh/config
    #      echo "  IdentityFile ~/.ssh/aur"      >> ~/.ssh/config
    #      echo "  User aur"                     >> ~/.ssh/config
    #      chmod -vR 600 ~/.ssh/*
    #      ssh-keyscan -v -t "rsa,dsa,ecdsa,ed25519" aur.archlinux.org >> ~/.ssh/known_hosts
    #      echo "$AUR_KEY" > ~/.ssh/aur
    #      chmod -vR 600 ~/.ssh/*
    #      ssh-keygen -vy -f ~/.ssh/aur > ~/.ssh/aur.pub
    #      chmod -vR 600 ~/.ssh/*

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Linux - Install apt dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: makepkg curl
          version: 1.0

      - name: Trigger Open Build Service and Copr
        shell: bash
        env:
          MESSAGE: ${{ github.event.inputs.text }}
          SUBMIT_FACTORY: ${{ github.event.inputs.publish_suse }}
          PUBLISH_OBS: ${{ github.event.inputs.publish_obs }}
          PUBLISH_COPR: ${{ github.event.inputs.publish_copr }}
          OBS_USER: ${{ secrets.OBS_USER }}
          EMAIL: ${{ secrets.EMAIL }}
          USER: ${{ github.actor }}
          PUBLISH_AUR: ${{ github.event.inputs.publish_aur }}
          OBS_PASSWORD: ${{ secrets.OBS_PASSWORD }}
          COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
          COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
          INPUT_VERSION: ${{ github.event.inputs.tag }}
        run: |
          export MESSAGE="$(echo -e "${MESSAGE}")"
          echo "Version is ${INPUT_VERSION}"
          if [[ "$PUBLISH_AUR" == "true" ]]; then . ./script/generate_pkgbuild.sh; fi
          if [[ "$PUBLISH_OBS" == "true" ]]; then . ./script/trigger_open_build_service.sh; fi
          if [[ "$PUBLISH_COPR" == "true" ]]; then pip install copr; python3 ./script/trigger_community_projects.py; fi
       #   . ./script/upload_aur.sh

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@master
        if: github.event.inputs.publish_aur == 'true'
        with:
           pkgname: nekobox
           pkgbuild: ./PKGBUILD
           commit_username: ${{ github.actor }}
           commit_email: email@email.email
           ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
           commit_message: Update AUR package
           ssh_keyscan_types: rsa,ecdsa,ed25519

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@master
        if: github.event.inputs.publish_aur == 'true'
        with:
           pkgname: nekobox-git
           pkgbuild: ./aur_git/PKGBUILD
           commit_username: ${{ github.actor }}
           commit_email: email@email.email
           ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
           commit_message: Update AUR package
           ssh_keyscan_types: rsa,ecdsa,ed25519

  build-cpp:
    name: Build windows binaries
    permissions:
      contents: read
    needs:
      - build-go
    strategy:
      matrix:
        include:
          - platform: windows-11-arm
            target: arm64
            qt_version: 6.11.0
            triplet: arm64-windows
            allow: ${{ github.event.inputs.build_windows_arm64 }}
          - platform: windows-latest
            target: x86_64
            qt_version: 6.10.0
            triplet: x64-windows
            allow: ${{ github.event.inputs.build_windows_x64 }}
          - platform: windows-latest
            target: x86
            qt_version: 6.10.0
            triplet: x86-windows
            allow: ${{ github.event.inputs.build_windows_x86 }}
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      INPUT_VERSION: ${{ github.event.inputs.tag }}
    steps:
      - name: Checking out sources
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        uses: actions/checkout@main
        with:
          ref: 'main'
          submodules: "true"

      - name: Setup Ninja
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        uses: qr243vbi/setup-ninja@master

      - name: Install NSIS
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true' && matrix.target != 'arm64'
        uses: negrutiu/nsis-install@v2
        with:
          arch: ${{ matrix.target }}

      - name: Install Customized Qt
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true' && matrix.target != 'arm64'
        uses: qr243vbi/qt6windows7@main
        with:
          version: ${{ matrix.qt_version }}_${{ matrix.target }}

      - name: Install Qt
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true' && matrix.target == 'arm64'
        uses: jurplel/install-qt-action@v4.3.0
        with:
          version: ${{ matrix.qt_version }}
          setup-python: true
          cache: true
          modules: qtcharts
          cache-key-prefix: QtCache-${{ matrix.platform }}-${{ matrix.target }}

      - name: Install MSVC compiler
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.target }}

      - name: vcpkg build
        uses: qr243vbi/vcpkg-action@master
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        id: vcpkg
        with:
          pkgs: thrift boost-filesystem boost-dll boost-headers boost-bimap lmdb
          triplet: ${{ matrix.triplet }}
          repository: qr243vbi/vcpkg
          vcpkg-subdir: ..\..\src
          token: ${{ secrets.UPLOAD_TOKEN }}
          
      - name: Download Artifacts
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        uses: actions/download-artifact@main
        with:
          path: download-artifact

      - name: Download Srslist
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        shell: bash
        run: |
          curl -fLso "srslist.json" "https://github.com/qr243vbi/ruleset/raw/refs/heads/rule-set/srslist.json"
          mkdir build

      - name: Cache Builds
        id: cache-common
        if: github.event.inputs.source_only  != 'true' && matrix.allow == 'true'
        uses: actions/cache@main
        with:
          path: build
          key: NinjaCache-${{ matrix.platform }}-${{ matrix.target }}-${{ github.event.inputs.tag }}

      - name: Install Zip, Curl, Jq, UPX
        uses: ConorMacBride/install-package@v1
        with:
          choco: zip curl jq upx

      - name: Windows - Generate MakeFile and Build
        if: matrix.allow == 'true' && github.event.inputs.source_only  != 'true'
        shell: bash
        run: |
          TOOLCHAIN=`realpath '${{ github.workspace }}/../../src/scripts/buildsystems/vcpkg.cmake'`
          TOOLCHAIN="$(cygpath -w "${TOOLCHAIN}")"
          if [[ ${{ github.event.inputs.skip_updater }} == 'true' ]]; then export SKIP_UPDATE_BUTTON=ON; else export SKIP_UPDATE_BUTTON=OFF; fi
          cmake -DBUILD_GO_PARTS=ON -GNinja -DCMAKE_TOOLCHAIN_FILE="${TOOLCHAIN}" '-DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}' -DVCPKG_MANIFEST_MODE=OFF -DSKIP_UPDATER="${SKIP_UPDATE_BUTTON}" -DCMAKE_BUILD_TYPE=Release "-DNKR_DEFAULT_VERSION=${INPUT_VERSION}" "-DBUILD_GO_PARTS=OFF" -S . -B build
          cmake --build build --config Release --verbose
          ./script/deploy_windows.sh "${{ matrix.target }}"

      - name: Tar files
        shell: bash
        if: matrix.allow == 'true' && github.event.inputs.source_only  != 'true'
        run: tar czvf artifacts.tgz ./deployment

      - name: Uploading Artifact
        if: matrix.allow == 'true' && github.event.inputs.source_only  != 'true'
        uses: actions/upload-artifact@main
        with:
          name: nekobox-${{ github.sha }}-${{ matrix.platform }}-${{ matrix.target }}-Qt${{ matrix.qt_version }}
          path: artifacts.tgz

  build-cpp-linux:
    name: Build linux binaries
    permissions:
      contents: write
      actions: read
    needs:
      - build-go
    strategy:
      matrix:
        include:
          - platform: ubuntu-24.04
            target: amd64
            target1: x86_64
            target2: x86_64
            allow: ${{ github.event.inputs.build_ubuntu }}
          - platform: ubuntu-24.04-arm
            target: arm64
            target1: aarch64
            target2: aarch64
            allow: ${{ github.event.inputs.build_ubuntu_arm }}
          - platform: ubuntu-24.04
            target: 386
            target1: i686
            target2: i386
            allow: ${{ github.event.inputs.build_ubuntu_32 }}
          - platform: ubuntu-24.04-arm
            target: arm
            target1: armhf
            target2: armhf
            allow: ${{ github.event.inputs.build_ubuntu_arm_32 }}
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      INPUT_VERSION: ${{ github.event.inputs.tag }}
    steps:
      - name: Checking out sources
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        uses: actions/checkout@main
        with:
          ref: 'main'
          submodules: "true"

      - name: Download Artifacts
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        uses: actions/download-artifact@main
        with:
          path: download-artifact

      - name: Download Srslist
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        shell: bash
        run: |
          curl -fLso "srslist.json" "https://github.com/qr243vbi/ruleset/raw/refs/heads/rule-set/srslist.json"
          mkdir build

      - name: Cache Builds
        id: cache-common
        if: github.event.inputs.source_only  != 'true' && matrix.allow == 'true'
        uses: actions/cache@main
        with:
          path: build
          key: CommonCache-${{ matrix.platform }}-${{ matrix.target }}-${{ github.event.inputs.tag }}

 #     - name: Cache Containers
  #      id: cache-common-containers
   #     if: github.event.inputs.source_only  != 'true' && matrix.allow == 'true'
    #    uses: actions/cache@v4.2.3
     #   with:
      #    path: ~/.local/share/containers
       #   key: CommonCachePodman-${{ matrix.platform }}-${{ matrix.target }}-${{ github.event.inputs.tag }}

 #     - name: Linux - Install apt dependencies
  #      if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
   #     uses: awalsh128/cache-apt-pkgs-action@latest
    #    with:
     #     packages: podman podman-compose
      #    version: 1.0

      - name: Cache Docker images.
        uses: AllySummers/docker-cache@main
        with:
          key: docker-${{ matrix.platform }}-${{ matrix.target }}-${{ hashFiles('script/Dockerfile') }}

      - name: Download linuxdeploy
        uses: ethanjli/cached-download-action@main
        with:
          url: https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-${{ matrix.target2 }}.AppImage
          destination: linuxdeploy-${{ matrix.target2 }}.AppImage

      - name: Download linuxdeploy-plugin-qt
        uses: ethanjli/cached-download-action@main
        with:
          url: https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-${{ matrix.target2 }}.AppImage
          destination: linuxdeploy-plugin-qt-${{ matrix.target2 }}.AppImage

      - name: Download appimagetool
        uses: ethanjli/cached-download-action@main
        with:
          url: https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-${{ matrix.target1 }}.AppImage
          destination: appimagetool-${{ matrix.target1 }}.AppImage

      - name: Linux - Generate MakeFile and Build
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        shell: bash
        env:
          GUEST_ARCH: ${{ matrix.target }}
        run: |
          if [[ ${{ github.event.inputs.skip_updater }} == 'true' ]]; then export SKIP_UPDATE_BUTTON=ON; else export SKIP_UPDATE_BUTTON=OFF; fi
          echo "UNAME=${GUEST_ARCH}" >> .ENV
          echo "INPUT_VERSION=${INPUT_VERSION}" >> .ENV
          echo "SKIP_UPDATE_BUTTON=${SKIP_UPDATE_BUTTON}" >> .ENV
          docker compose up --force-recreate --build

      - name: Linux - Publish
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true' && github.event.inputs.publish  == 'true'
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        run: |
          gh release upload "$INPUT_VERSION" ./deployment/* --clobber

      - name: Tar files
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        shell: bash
        run: tar czvf artifacts.tgz ./deployment

      - name: Uploading Artifact
        if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
        uses: actions/upload-artifact@main
        with:
          name: nekobox-${{ github.sha }}-${{ matrix.platform }}-${{ matrix.target }}
          path: artifacts.tgz
  #
  # build-cpp-linux:
  #   name: Build linux binaries
  #   permissions:
  #     contents: write
  #     actions: read
  #   needs:
  #     - build-go
  #   strategy:
  #     matrix:
  #       include:
  #         - platform: ubuntu-24.04
  #           qt_version: 6.10.2
  #           target: amd64
  #           allow: ${{ github.event.inputs.build_ubuntu }}
  #         - platform: ubuntu-24.04-arm
  #           qt_version: 6.10.2
  #           target: arm64
  #           allow: ${{ github.event.inputs.build_ubuntu_arm }}
  #     fail-fast: false
  #   runs-on: ${{ matrix.platform }}
  #   env:
  #     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  #     INPUT_VERSION: ${{ github.event.inputs.tag }}
  #   steps:
  #     - name: Checking out sources
  #       if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
  #       uses: actions/checkout@main
  #       with:
  #         ref: 'main'
  #         submodules: "false"
  #
  #     - name: Download Artifacts
  #       if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
  #       uses: actions/download-artifact@v4.3.0
  #       with:
  #         path: download-artifact
  #
  #     - name: Install Qt
  #       if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
  #       uses: jurplel/install-qt-action@v4.3.0
  #       with:
  #         version: ${{ matrix.qt_version }}
  #         setup-python: true
  #         cache: true
  #         modules: qtcharts
  #         cache-key-prefix: QtCache-${{ matrix.platform }}-${{ matrix.target }}
  #
  #     - name: Download Srslist
  #       if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
  #       shell: bash
  #       run: |
  #         curl -fLso "srslist.json" "https://github.com/qr243vbi/ruleset/raw/refs/heads/rule-set/srslist.json"
  #         mkdir build
  #
  #     - name: Linux - Install apt dependencies
  #       if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
  #       uses: awalsh128/cache-apt-pkgs-action@latest
  #       with:
  #         packages: libfuse2 patchelf squashfs-tools openssl-dev openssl thrift-compiler libthrift-dev libboost-dev
  #         version: 1.0
  #
  #     - name: Cache Builds
  #       id: cache-common
  #       if: github.event.inputs.source_only  != 'true' && matrix.allow == 'true'
  #       uses: actions/cache@v4.2.3
  #       with:
  #         path: build
  #         key: CommonCache-${{ matrix.platform }}-${{ matrix.target }}-${{ github.event.inputs.tag }}
  #
  #     - name: Linux - Generate MakeFile and Build
  #       if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
  #       shell: bash
  #       run: |
  #         cd build
  #         if [[ ${{ github.event.inputs.skip_updater }} == 'true' ]]; then export SKIP_UPDATE_BUTTON=ON; else export SKIP_UPDATE_BUTTON=OFF; fi
  #         cmake -GNinja -DSKIP_UPDATE_BUTTON="${SKIP_UPDATE_BUTTON}" -DCMAKE_BUILD_TYPE=Release "-DNKR_DEFAULT_VERSION=${INPUT_VERSION}" ..
  #         ninja
  #         cd ..
  #         if [[ "${{ github.event.inputs.publish }}" == "true" ]]
  #         then
  #           export UPLOAD_WITH_GH=yes
  #           export GH_TOKEN='${{ secrets.UPLOAD_TOKEN }}'
  #         fi
  #         bash -x ./script/deploy_linux64.sh
  #
  #     - name: Tar files
  #       if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
  #       shell: bash
  #       run: tar czvf artifacts.tgz ./deployment
  #
  #     - name: Uploading Artifact
  #       if: matrix.allow == 'true' && github.event.inputs.source_only != 'true'
  #       uses: actions/upload-artifact@v4.6.2
  #       with:
  #         name: nekobox-${{ github.sha }}-${{ matrix.platform }}-${{ matrix.target }}-Qt${{ matrix.qt_version }}
  #         path: artifacts.tgz

  publish:
    name: Pack & Publish Release
    runs-on: windows-latest
    needs:
      - build-cpp
    permissions:
      contents: write
      actions: read
    env:
      INPUT_VERSION: ${{ github.event.inputs.tag }}
    if: github.event.inputs.publish == 'true' && github.event.inputs.source_only != 'true'
    steps:
      - name: Checking out sources
        uses: actions/checkout@main
        with:
          ref: 'main'
          submodules: "true"
      - name: Download Artifacts
        uses: actions/download-artifact@main
        with:
          path: download-artifact
      - name: Install Zip, Curl, Jq
        uses: ConorMacBride/install-package@v1
        with:
          choco: zip curl jq
      - name: Pack
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_TOKEN }}
          INPUT_VERSION: ${{ github.event.inputs.tag }}
          EMAIL: ${{ secrets.EMAIL }}
          UPLOAD_WITH_GH: yes
          CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
          GH_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        run: |
          source script/env_deploy.sh
          find . -name artifacts.tgz | xargs -n1 tar xvzf
          ##
          cd deployment
          ####
          if [[ -f "$version_standalone-windows64-installer.exe" ]]; then
            gh release upload "${INPUT_VERSION}" "$version_standalone-windows64-installer.exe" --clobber
            gh release upload "${INPUT_VERSION}" "$version_standalone-windows64.zip" --clobber
          fi
          ####
          if [[ -f "$version_standalone-windows-arm64-installer.exe" ]]; then
            gh release upload "${INPUT_VERSION}" "$version_standalone-windows-arm64-installer.exe" --clobber
            gh release upload "${INPUT_VERSION}" "$version_standalone-windows-arm64.zip" --clobber
          fi
          ####
          if [[ -f "$version_standalone-windows32-installer.exe" ]]; then
            gh release upload "${INPUT_VERSION}" "$version_standalone-windows32-installer.exe" --clobber
            gh release upload "${INPUT_VERSION}" "$version_standalone-windows32.zip" --clobber
          fi
          if [[ '${{ github.event.inputs.publish_winget }}' == 'true' && -f $version_standalone-windows32.zip && -f $version_standalone-windows64.zip && -f $version_standalone-windows-arm64.zip ]]
          then
            pushd ..
            bash ./script/trigger_winget_pkgs.sh
            popd
          fi
          if [[ '${{ github.event.inputs.publish_chocolatey }}' == 'true' && -f $version_standalone-windows32.zip && -f $version_standalone-windows64.zip ]]
          then
            pushd ../script
            bash chocolatey_push.sh
            popd
          fi



